const keywords = {
  __COLUMN: '__COLUMN',
  __LINE: '__LINE',
  BEGIN: 'BEGIN',
  CALL: 'CALL',
  ECHO: 'ECHO',
  ELSE: 'ELSE',
  ENDFUNC: 'ENDFUNC',
  ENDIF: 'ENDIF',
  ENDPROC: 'ENDPROC',
  ENDWHILE: 'ENDWHILE',
  EXIT: 'EXIT',
  FUNC: 'FUNC',
  IF: 'IF',
  INPUT: 'INPUT',
  LET: 'LET',
  PAUSE: 'PAUSE',
  PROC: 'PROC',
  REM: 'REM',
  RETURN: 'RETURN',
  STRUCT: 'STRUCT',
  VAR: 'VAR',
  WHILE: 'WHILE',
};

module.exports = keywords;
